### ISSUE TITLE
[Feature] gradle 관리 

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/FlowMovie#1]
## 📚 To-do

- [x] gradle.kts 적용
- [x] buildSrc로 버전관리 적용
- [x] Libraries 의존성 추가
- [x] Secret Key 관리
