### ISSUE TITLE
[Feature] 영화 link 연결

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/FlowMovie#16]
## 📚 To-do

- [x] MovieModle에 Link 속성 추가
- [x] Intent ActionView를 통해 브라우저로 연결
- [x] 앱 실행시, 브라우저로 다녀온 후에 키보드가 올라오는 문제 수정
