### ISSUE TITLE
[Feature] 검색어 저장 Data모듈 정의

### ISSUE THREAD

**Issue by wjchoi96** [wjchoi96/FlowMovie#9]
## 📚 To-do

- [x] Local Recent Query 저장 
    - Room Dao 정의
    - Entitiy 정의
- [x] DataSource 정의
- [x] MovieRepositoryImpl에 RecentQuery 관련 함수 정의
- [x] Dao Android Test Code 작성
- [x] MovieRepositoryImpl TestCase 추가
